debug = true

[db]
    name  = "test"
    host    = "127.0.0.1"
    port    = 3306
    user    = "root"
    pass    = "123456"
    ssl_mode = "false"
    database = "test"
    whitelist=["logs","users"]
    blacklist=[]

[model]
    package="model"
    import="github.com/teamlint/gen/model"
    enabled=true
    guregu=false
    tags=["gorm","json"]
    # template="templates/model.tpl"

[query]
    package="query"
    import="github.com/teamlint/gen/model/query"
    enabled=true
    base=true
    
[service]
    package="service"
    enabled=true
    template=""

[controller]
    package="controller"
    enabled=true
    template=""

# [tables.users.aliases]
#   # up_plural     = "LogQuery"
#   # up_singular   = "Log"
#   # down_plural   = "logQuery"
#   # down_singular = "log"

[tables.users.columns.is_approved]
  alias = ""
  type     = "bool"

[tables.users.columns.gender]
  alias = "Sex"
  type     = "UserGender"

# [aliases.tables.users.columns]
#   pid = "PID"
#   money = "Price"


# templates = [
#   # "/venjiang/go/src/github.com/volatiletech/sqlboiler/templates",
#   # "/venjiang/go/src/github.com/volatiletech/sqlboiler/templates_test",
#   "/venjiang/go/src/test/sql/boiler/orm/templates"
# ]

# [[types]]
#   [types.match]
#     type = "null.Time"
#     nullable = true
#   [types.replace]
#     type = "*time.Time"

# [[types]]
#   [types.match]
#     type = "null.String"
#     nullable = true
#   [types.replace]
#     type = "string"


# [[types]]
#   [types.match]
#     type = "null.Int"
#     nullable = true
#   [types.replace]
#     type = "int"

  #[types.imports]
  #  third_party = ['"github.com/me/mynull"']

